# Generated by Django 4.1.3 on 2022-11-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Normal User', 'Normal User'), ('Shop User', 'Shop User'), ('Admin', 'Admin')], max_length=250),
        ),
    ]
